/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsWaferOverlayRouteImport } from './routes/tools.wafer-overlay'
import { Route as ToolsIbeThicknessRouteImport } from './routes/tools.ibe-thickness'
import { Route as ToolsFilmThicknessRouteImport } from './routes/tools.film-thickness'
import { Route as ToolsCsvTestMergeRouteImport } from './routes/tools.csv-test-merge'
import { Route as ToolsCpHistogramRouteImport } from './routes/tools.cp-histogram'
import { Route as ToolsAoiMapDiffRouteImport } from './routes/tools.aoi-map-diff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWaferOverlayRoute = ToolsWaferOverlayRouteImport.update({
  id: '/tools/wafer-overlay',
  path: '/tools/wafer-overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIbeThicknessRoute = ToolsIbeThicknessRouteImport.update({
  id: '/tools/ibe-thickness',
  path: '/tools/ibe-thickness',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFilmThicknessRoute = ToolsFilmThicknessRouteImport.update({
  id: '/tools/film-thickness',
  path: '/tools/film-thickness',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCsvTestMergeRoute = ToolsCsvTestMergeRouteImport.update({
  id: '/tools/csv-test-merge',
  path: '/tools/csv-test-merge',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCpHistogramRoute = ToolsCpHistogramRouteImport.update({
  id: '/tools/cp-histogram',
  path: '/tools/cp-histogram',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAoiMapDiffRoute = ToolsAoiMapDiffRouteImport.update({
  id: '/tools/aoi-map-diff',
  path: '/tools/aoi-map-diff',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/aoi-map-diff': typeof ToolsAoiMapDiffRoute
  '/tools/cp-histogram': typeof ToolsCpHistogramRoute
  '/tools/csv-test-merge': typeof ToolsCsvTestMergeRoute
  '/tools/film-thickness': typeof ToolsFilmThicknessRoute
  '/tools/ibe-thickness': typeof ToolsIbeThicknessRoute
  '/tools/wafer-overlay': typeof ToolsWaferOverlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/aoi-map-diff': typeof ToolsAoiMapDiffRoute
  '/tools/cp-histogram': typeof ToolsCpHistogramRoute
  '/tools/csv-test-merge': typeof ToolsCsvTestMergeRoute
  '/tools/film-thickness': typeof ToolsFilmThicknessRoute
  '/tools/ibe-thickness': typeof ToolsIbeThicknessRoute
  '/tools/wafer-overlay': typeof ToolsWaferOverlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/aoi-map-diff': typeof ToolsAoiMapDiffRoute
  '/tools/cp-histogram': typeof ToolsCpHistogramRoute
  '/tools/csv-test-merge': typeof ToolsCsvTestMergeRoute
  '/tools/film-thickness': typeof ToolsFilmThicknessRoute
  '/tools/ibe-thickness': typeof ToolsIbeThicknessRoute
  '/tools/wafer-overlay': typeof ToolsWaferOverlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tools/aoi-map-diff'
    | '/tools/cp-histogram'
    | '/tools/csv-test-merge'
    | '/tools/film-thickness'
    | '/tools/ibe-thickness'
    | '/tools/wafer-overlay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tools/aoi-map-diff'
    | '/tools/cp-histogram'
    | '/tools/csv-test-merge'
    | '/tools/film-thickness'
    | '/tools/ibe-thickness'
    | '/tools/wafer-overlay'
  id:
    | '__root__'
    | '/'
    | '/tools/aoi-map-diff'
    | '/tools/cp-histogram'
    | '/tools/csv-test-merge'
    | '/tools/film-thickness'
    | '/tools/ibe-thickness'
    | '/tools/wafer-overlay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsAoiMapDiffRoute: typeof ToolsAoiMapDiffRoute
  ToolsCpHistogramRoute: typeof ToolsCpHistogramRoute
  ToolsCsvTestMergeRoute: typeof ToolsCsvTestMergeRoute
  ToolsFilmThicknessRoute: typeof ToolsFilmThicknessRoute
  ToolsIbeThicknessRoute: typeof ToolsIbeThicknessRoute
  ToolsWaferOverlayRoute: typeof ToolsWaferOverlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/wafer-overlay': {
      id: '/tools/wafer-overlay'
      path: '/tools/wafer-overlay'
      fullPath: '/tools/wafer-overlay'
      preLoaderRoute: typeof ToolsWaferOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ibe-thickness': {
      id: '/tools/ibe-thickness'
      path: '/tools/ibe-thickness'
      fullPath: '/tools/ibe-thickness'
      preLoaderRoute: typeof ToolsIbeThicknessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/film-thickness': {
      id: '/tools/film-thickness'
      path: '/tools/film-thickness'
      fullPath: '/tools/film-thickness'
      preLoaderRoute: typeof ToolsFilmThicknessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/csv-test-merge': {
      id: '/tools/csv-test-merge'
      path: '/tools/csv-test-merge'
      fullPath: '/tools/csv-test-merge'
      preLoaderRoute: typeof ToolsCsvTestMergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/cp-histogram': {
      id: '/tools/cp-histogram'
      path: '/tools/cp-histogram'
      fullPath: '/tools/cp-histogram'
      preLoaderRoute: typeof ToolsCpHistogramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/aoi-map-diff': {
      id: '/tools/aoi-map-diff'
      path: '/tools/aoi-map-diff'
      fullPath: '/tools/aoi-map-diff'
      preLoaderRoute: typeof ToolsAoiMapDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsAoiMapDiffRoute: ToolsAoiMapDiffRoute,
  ToolsCpHistogramRoute: ToolsCpHistogramRoute,
  ToolsCsvTestMergeRoute: ToolsCsvTestMergeRoute,
  ToolsFilmThicknessRoute: ToolsFilmThicknessRoute,
  ToolsIbeThicknessRoute: ToolsIbeThicknessRoute,
  ToolsWaferOverlayRoute: ToolsWaferOverlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
