// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeFilmThickness(arg1:main.FilmThicknessAnalyzeRequest):Promise<main.FilmThicknessAnalyzeResult>;

export function SaveBase64Image(arg1:string,arg2:string):Promise<string>;

export function SaveMergedTestItemExcel(arg1:main.MergedTestItemExcelRequest):Promise<string>;

export function SaveWaferMapPNG(arg1:main.WaferMapExportRequest):Promise<string>;

export function SelectFilmThicknessOutputRoot(arg1:string):Promise<string>;

export function SetAppearance(arg1:string):Promise<void>;
